package notification

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/smtp"
	"net/url"
	"strings"
	"time"
)

// EmailTimeout bounds one SMTP send.
const EmailTimeout = 10 * time.Second

// ErrSMTPNotConfigured is returned by EmailSink.Send when no smtp_url
// secret is available (the secrets registry entry documented in
// docs/design/billing.md §4); the evaluator records the channel as
// skipped rather than failing the whole alert.
var ErrSMTPNotConfigured = errors.New("notification: smtp_url is not configured")

// Transport sends one already-composed RFC 5322 message. EmailSink's
// default implementation is SMTPTransport (net/smtp, STARTTLS); tests
// inject a fake to assert on the composed message without a network.
type Transport interface {
	Send(ctx context.Context, from string, to []string, msg []byte) error
}

// EmailSink implements screener/alerts.EmailSink: it renders a minimal
// RFC 5322 message (plain text — alert bodies are already the fixed
// measurement text from screener/alerts/message.go) and hands it to
// Transport. From is the envelope/header From address.
type EmailSink struct {
	Transport Transport
	From      string
}

func (e *EmailSink) Send(ctx context.Context, to, subject, body string) error {
	if e.Transport == nil {
		return ErrSMTPNotConfigured
	}
	if _, err := mail.ParseAddress(to); err != nil {
		return fmt.Errorf("notification: invalid recipient: %w", err)
	}
	from := e.From
	if from == "" {
		from = "alerts@arb-chain-bot.local"
	}
	msg := buildMessage(from, to, subject, body)
	return e.Transport.Send(ctx, from, []string{to}, msg)
}

// buildMessage renders a minimal, header-injection-safe RFC 5322
// message: Subject/To/From come from the alert rule and are stripped of
// CR/LF before use (a rule's email_to is validated as a single address
// by screener.Rule.Validate, and subject is generated by
// screener/alerts/message.go, but this stays defensive regardless).
func buildMessage(from, to, subject, body string) []byte {
	clean := func(s string) string {
		s = strings.ReplaceAll(s, "\r", " ")
		return strings.ReplaceAll(s, "\n", " ")
	}
	var b strings.Builder
	fmt.Fprintf(&b, "From: %s\r\n", clean(from))
	fmt.Fprintf(&b, "To: %s\r\n", clean(to))
	fmt.Fprintf(&b, "Subject: %s\r\n", clean(subject))
	b.WriteString("MIME-Version: 1.0\r\n")
	b.WriteString("Content-Type: text/plain; charset=utf-8\r\n")
	b.WriteString("\r\n")
	b.WriteString(body)
	return []byte(b.String())
}

// SMTPTransport sends over net/smtp with STARTTLS, configured from a
// smtp:// or smtps:// URL (secrets registry "smtp_url",
// docs/design/billing.md §4): smtp://user:pass@host:587 (STARTTLS,
// default) or smtps://user:pass@host:465 (implicit TLS).
type SMTPTransport struct {
	// RawURL is read fresh on every Send (the secrets chain may rotate
	// it); a resolver function, not a stored string, so a vault write
	// applies immediately like every other "applies: immediately"
	// provider secret.
	URL func(ctx context.Context) string
}

func (t *SMTPTransport) Send(ctx context.Context, from string, to []string, msg []byte) error {
	raw := ""
	if t.URL != nil {
		raw = t.URL(ctx)
	}
	if raw == "" {
		return ErrSMTPNotConfigured
	}
	u, err := url.Parse(raw)
	if err != nil {
		return fmt.Errorf("notification: invalid smtp_url: %w", err)
	}
	host := u.Hostname()
	port := u.Port()
	implicitTLS := u.Scheme == "smtps"
	if port == "" {
		if implicitTLS {
			port = "465"
		} else {
			port = "587"
		}
	}
	addr := net.JoinHostPort(host, port)
	var auth smtp.Auth
	if u.User != nil {
		pass, _ := u.User.Password()
		auth = smtp.PlainAuth("", u.User.Username(), pass, host)
	}

	dialer := &net.Dialer{Timeout: EmailTimeout}
	conn, err := dialer.DialContext(ctx, "tcp", addr)
	if err != nil {
		return fmt.Errorf("notification: smtp dial: %w", err)
	}
	_ = conn.SetDeadline(time.Now().Add(EmailTimeout))
	if implicitTLS {
		conn = tls.Client(conn, &tls.Config{ServerName: host, MinVersion: tls.VersionTLS12})
	}
	client, err := smtp.NewClient(conn, host)
	if err != nil {
		_ = conn.Close()
		return fmt.Errorf("notification: smtp client: %w", err)
	}
	defer func() { _ = client.Close() }()
	if !implicitTLS {
		if ok, _ := client.Extension("STARTTLS"); ok {
			if err := client.StartTLS(&tls.Config{ServerName: host, MinVersion: tls.VersionTLS12}); err != nil {
				return fmt.Errorf("notification: starttls: %w", err)
			}
		}
	}
	if auth != nil {
		if err := client.Auth(auth); err != nil {
			return fmt.Errorf("notification: smtp auth: %w", err)
		}
	}
	if err := client.Mail(from); err != nil {
		return fmt.Errorf("notification: smtp mail from: %w", err)
	}
	for _, rcpt := range to {
		if err := client.Rcpt(rcpt); err != nil {
			return fmt.Errorf("notification: smtp rcpt to: %w", err)
		}
	}
	w, err := client.Data()
	if err != nil {
		return fmt.Errorf("notification: smtp data: %w", err)
	}
	if _, err := w.Write(msg); err != nil {
		return err
	}
	if err := w.Close(); err != nil {
		return err
	}
	return client.Quit()
}
