# Example: managed Redis with automatic failover, in-transit + at-rest
# encryption. Used for websocket fan-out and per-venue rate gates; the
# AUTH token is generated by the secrets module and never stored here.
resource "aws_elasticache_subnet_group" "this" {
  name       = var.name
  subnet_ids = var.subnet_ids
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id       = var.name
  description                = "arb ${var.name} fan-out + rate gates"
  engine                     = "redis"
  engine_version             = "7.1"
  node_type                  = var.node_type
  num_node_groups            = 1
  replicas_per_node_group    = var.replicas_per_shard
  automatic_failover_enabled = true
  multi_az_enabled           = true
  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  kms_key_id                 = var.kms_key_arn
  subnet_group_name          = aws_elasticache_subnet_group.this.name
  snapshot_retention_limit   = 3
  tags                       = var.tags
}
